#address:
#  - Address Line 1
#  - Address Line 2
#  - City, State, AZ 12345

#phone: 480-727-1234

email: robotics@asu.edu

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
      image:
        feature: 18470766606_05e0dfb6cc_k-1024x683.jpg
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

base_path: "/asurobotics"
#base_path: ""

kramdown:
  input: GFM
  auto_ids: true
highlighter: rouge

organization_name: ASU Robotics
title: ASU Robotics

menu:
  - name: Faculty
    link: faculty
  - name: Labs
    link: labs
  - name: Courses
    link: courses
  - name: Resources
    link: resources
  - name: Get Involved
    link: get-involved
  - name: News
    link: news

faculty_tags:
  - name: poly
    link: faculty_poly
  - name: tempe
    link: faculty_tempe
  - name: control
    link: control
  - name: design
    link: design


tags: a,b,c,d
